### ISSUE TITLE
cephfs: e2e test fails deleting cloned PVCs

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1359]
Occasionally different CentOS CI jobs fail the CephFS cloning e2e tests. Running `/retest ci/centos/mini-e2e_k8s-1.18.5` (or whatever job failed) often makes it pass with the 2nd time.

The error is caused during the cleanup of parallel cloned PVCs:

```
Aug 11 12:04:06.250: INFO: Waiting for pod csi-cephfs-demo-pod to be deleted
Aug 11 12:04:06.253: INFO: csi-cephfs-demo-pod app  to be deleted (0 seconds elapsed)
Aug 11 12:04:08.257: INFO: csi-cephfs-demo-pod app  to be deleted (2 seconds elapsed)
Aug 11 12:04:10.257: INFO: csi-cephfs-demo-pod app  to be deleted (4 seconds elapsed)
Aug 11 12:04:12.256: INFO: Deleting PersistentVolumeClaim csi-cephfs-pvc on namespace cephfs-7887
Aug 11 12:04:12.269: INFO: waiting for PVC csi-cephfs-pvc in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteMany],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (0 seconds elapsed)
Aug 11 12:04:14.279: INFO: waiting for PVC csi-cephfs-pvc in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteMany],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (2 seconds elapsed)
Aug 11 12:04:16.279: INFO: waiting for PVC csi-cephfs-pvc in state &PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (4 seconds elapsed)
Aug 11 12:04:18.279: INFO: waiting for PVC csi-cephfs-pvc in state &PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (6 seconds elapsed)
Aug 11 12:04:18.293: INFO: Waiting for pod cephfs-78872 to be deleted
Aug 11 12:04:18.296: INFO: cephfs-78872 app  to be deleted (0 seconds elapsed)
Aug 11 12:04:18.296: INFO: Waiting for pod cephfs-78871 to be deleted
Aug 11 12:04:18.310: INFO: Waiting for pod cephfs-78870 to be deleted
Aug 11 12:04:18.310: INFO: cephfs-78871 app  to be deleted (0 seconds elapsed)
Aug 11 12:04:18.313: INFO: cephfs-78870 app  to be deleted (0 seconds elapsed)
Aug 11 12:04:20.309: INFO: cephfs-78872 app  to be deleted (2 seconds elapsed)
Aug 11 12:04:20.314: INFO: cephfs-78871 app  to be deleted (2 seconds elapsed)
Aug 11 12:04:20.317: INFO: cephfs-78870 app  to be deleted (2 seconds elapsed)
Aug 11 12:04:22.299: INFO: Deleting PersistentVolumeClaim cephfs-78872 on namespace cephfs-7887
Aug 11 12:04:22.310: INFO: waiting for PVC cephfs-78872 in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteMany],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (0 seconds elapsed)
Aug 11 12:04:22.314: INFO: Deleting PersistentVolumeClaim cephfs-78871 on namespace cephfs-7887
Aug 11 12:04:22.317: INFO: Deleting PersistentVolumeClaim cephfs-78870 on namespace cephfs-7887
Aug 11 12:04:22.342: INFO: waiting for PVC cephfs-78871 in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteMany],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (0 seconds elapsed)
Aug 11 12:04:22.346: INFO: waiting for PVC cephfs-78870 in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteMany],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (0 seconds elapsed)
Aug 11 12:04:24.315: INFO: waiting for PVC cephfs-78872 in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteMany],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (2 seconds elapsed)
...
Aug 11 12:14:22.315: INFO: waiting for PVC cephfs-78872 in state &PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (600 seconds elapsed)
Aug 11 12:14:22.321: INFO: waiting for PVC cephfs-78872 in state &PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},}  to be deleted (600 seconds elapsed)
panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

	defer GinkgoRecover()

at the top of the goroutine that caused this panic.


goroutine 1872 [running]:
github.com/onsi/ginkgo.Fail(0x1b795db, 0x23, 0x0, 0x0, 0x0)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:267 +0xc8
github.com/ceph/ceph-csi/e2e.glob..func1.3.1.3.10.2(0xc00029ef20, 0xc000752390, 0xc000ef6640, 0x2, 0xc000f62440, 0x15, 0xc00053a8e8, 0x2, 0xc0003236c0, 0xc, ...)
	/go/src/github.com/ceph/ceph-csi/e2e/cephfs.go:594 +0x19a
created by github.com/ceph/ceph-csi/e2e.glob..func1.3.1.3.10
	/go/src/github.com/ceph/ceph-csi/e2e/cephfs.go:589 +0x7dd
```

**Comment by nixpanic** [comment]
Failed job: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/mini-e2e_k8s-1.18.5/162/console

**Comment by nixpanic** [comment]
Failed job: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/mini-e2e_k8s-1.17.8/136/console

**Comment by humblec** [comment]
Not sure this has anything to do with the common e2e functions we use , however its failing like below for RBD cloning too with below errors:


```
Aug 11 15:46:29.707: INFO: rbd-40590 app  is in Pending phase expected to be in Running  state (16 seconds elapsed)
Aug 11 15:46:29.727: INFO: rbd-40598 app  is in Pending phase expected to be in Running  state (16 seconds elapsed)
Aug 11 15:46:29.727: INFO: rbd-40595 app  is in Pending phase expected to be in Running  state (16 seconds elapsed)
Aug 11 15:46:29.727: INFO: rbd-40591 app  is in Pending phase expected to be in Running  state (24 seconds elapsed)
Aug 11 15:46:29.790: INFO: rbd-40596 app  is in Pending phase expected to be in Running  state (26 seconds elapsed)
Aug 11 15:46:29.816: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (26 seconds elapsed)
Aug 11 15:46:31.707: INFO: rbd-40590 app  is in Pending phase expected to be in Running  state (18 seconds elapsed)
Aug 11 15:46:31.731: INFO: rbd-40591 app  is in Pending phase expected to be in Running  state (26 seconds elapsed)
Aug 11 15:46:31.732: INFO: rbd-40598 app  is in Pending phase expected to be in Running  state (18 seconds elapsed)
Aug 11 15:46:31.789: INFO: rbd-40596 app  is in Pending phase expected to be in Running  state (28 seconds elapsed)
Aug 11 15:46:31.817: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (28 seconds elapsed)
Aug 11 15:46:33.708: INFO: rbd-40590 app  is in Pending phase expected to be in Running  state (20 seconds elapsed)
Aug 11 15:46:33.724: INFO: rbd-40598 app  is in Pending phase expected to be in Running  state (20 seconds elapsed)
Aug 11 15:46:33.789: INFO: rbd-40596 app  is in Pending phase expected to be in Running  state (30 seconds elapsed)
Aug 11 15:46:33.821: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (30 seconds elapsed)
Aug 11 15:46:35.708: INFO: rbd-40590 app  is in Pending phase expected to be in Running  state (22 seconds elapsed)
Aug 11 15:46:35.723: INFO: rbd-40598 app  is in Pending phase expected to be in Running  state (22 seconds elapsed)
Aug 11 15:46:35.816: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (32 seconds elapsed)
Aug 11 15:46:37.816: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (34 seconds elapsed)
Aug 11 15:46:39.821: INFO: ExecWithOptions {Command:[/bin/sh -c rbd ls --pool=replicapool --format=json] Namespace:rook-ceph PodName:rook-ceph-tools-7959b9f77c-b5w22 ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true}
Aug 11 15:46:39.821: INFO: >>> kubeConfig: /root/.kube/config
Aug 11 15:46:40.216: INFO: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21
[AfterEach] RBD
```

job: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/mini-e2e-helm_k8s-1.18.5/156/consoleFull

@Madhu-1 this is what I was referring to in our meeting.

**Comment by Madhu-1** [comment]
> Not sure this has anything to do with the common e2e functions we use , however its failing like below for RBD cloning too with below errors:
> 
> ```
> Aug 11 15:46:29.707: INFO: rbd-40590 app  is in Pending phase expected to be in Running  state (16 seconds elapsed)
> Aug 11 15:46:29.727: INFO: rbd-40598 app  is in Pending phase expected to be in Running  state (16 seconds elapsed)
> Aug 11 15:46:29.727: INFO: rbd-40595 app  is in Pending phase expected to be in Running  state (16 seconds elapsed)
> Aug 11 15:46:29.727: INFO: rbd-40591 app  is in Pending phase expected to be in Running  state (24 seconds elapsed)
> Aug 11 15:46:29.790: INFO: rbd-40596 app  is in Pending phase expected to be in Running  state (26 seconds elapsed)
> Aug 11 15:46:29.816: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (26 seconds elapsed)
> Aug 11 15:46:31.707: INFO: rbd-40590 app  is in Pending phase expected to be in Running  state (18 seconds elapsed)
> Aug 11 15:46:31.731: INFO: rbd-40591 app  is in Pending phase expected to be in Running  state (26 seconds elapsed)
> Aug 11 15:46:31.732: INFO: rbd-40598 app  is in Pending phase expected to be in Running  state (18 seconds elapsed)
> Aug 11 15:46:31.789: INFO: rbd-40596 app  is in Pending phase expected to be in Running  state (28 seconds elapsed)
> Aug 11 15:46:31.817: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (28 seconds elapsed)
> Aug 11 15:46:33.708: INFO: rbd-40590 app  is in Pending phase expected to be in Running  state (20 seconds elapsed)
> Aug 11 15:46:33.724: INFO: rbd-40598 app  is in Pending phase expected to be in Running  state (20 seconds elapsed)
> Aug 11 15:46:33.789: INFO: rbd-40596 app  is in Pending phase expected to be in Running  state (30 seconds elapsed)
> Aug 11 15:46:33.821: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (30 seconds elapsed)
> Aug 11 15:46:35.708: INFO: rbd-40590 app  is in Pending phase expected to be in Running  state (22 seconds elapsed)
> Aug 11 15:46:35.723: INFO: rbd-40598 app  is in Pending phase expected to be in Running  state (22 seconds elapsed)
> Aug 11 15:46:35.816: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (32 seconds elapsed)
> Aug 11 15:46:37.816: INFO: rbd-40594 app  is in Pending phase expected to be in Running  state (34 seconds elapsed)
> Aug 11 15:46:39.821: INFO: ExecWithOptions {Command:[/bin/sh -c rbd ls --pool=replicapool --format=json] Namespace:rook-ceph PodName:rook-ceph-tools-7959b9f77c-b5w22 ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true}
> Aug 11 15:46:39.821: INFO: >>> kubeConfig: /root/.kube/config
> Aug 11 15:46:40.216: INFO: backend images not matching kubernetes resource count,image count 22 kubernetes resource count 21
> [AfterEach] RBD
> ```
> 
> job: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/mini-e2e-helm_k8s-1.18.5/156/consoleFull
> 
> @Madhu-1 this is what I was referring to in our meeting.

Thanks @humblec let me add more backend testing for rbd images.

**Comment by humblec** [comment]
@Madhu-1 do need to track the RBD case in a separate issue?

**Comment by Madhu-1** [comment]
> @Madhu-1 do need to track the RBD case in a separate issue?

Yes please that helps

**Comment by humblec** [comment]
> > @Madhu-1 do need to track the RBD case in a separate issue?
> 
> Yes please that helps

Done. may be revisiting the e2e function or framework help to get rid of these kind of errors.

**Comment by Madhu-1** [comment]
one more cephfs clone failure https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/mini-e2e_k8s-1.17.8/299/console

**Comment by nixpanic** [comment]
CephFS again at https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/mini-e2e_k8s-1.17.8/325/console :
```
Aug 18 07:48:34.950: INFO: failed to delete pvc and app timed out waiting for the condition
panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

	defer GinkgoRecover()

at the top of the goroutine that caused this panic.


goroutine 1786 [running]:
github.com/onsi/ginkgo.Fail(0x1b29977, 0x23, 0x0, 0x0, 0x0)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:267 +0xc8
github.com/ceph/ceph-csi/e2e.glob..func1.3.1.3.9.6(0xc0004dcf20, 0xc00057e8a0, 0xc000446d90, 0x1, 0xc0000f1e40, 0x15, 0xc000b341a8, 0x2, 0xc000bd86c0, 0xc, ...)
	/go/src/github.com/ceph/ceph-csi/e2e/cephfs.go:544 +0x1ed
created by github.com/ceph/ceph-csi/e2e.glob..func1.3.1.3.9
	/go/src/github.com/ceph/ceph-csi/e2e/cephfs.go:538 +0xedb
make: *** [Makefile:147: run-e2e] Error 2
```

**Comment by Madhu-1** [comment]
one more failure https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/mini-e2e-helm_k8s-1.17.8/350/console

**Comment by nixpanic** [comment]
> Have we seen this issue recently with any of the PR runs ?

Yes, #1644 is getting hit a lot with this. I have seen it occasionally on others too, although not that many times in a single PR.

**Comment by Madhu-1** [comment]
This should be fixed in https://github.com/ceph/ceph-csi/pull/1671, please reopen if we see the issue again.
