### ISSUE TITLE
can't seem to get logging working with the v3.2.0 and master/canary version

### ISSUE THREAD

**Issue by f1-outsourcing** [ceph/ceph-csi#1807]
Sorry for asking, but I just do not seem to get this logging working. I have tried multiple combinations of logging arguments but I just do not seem to get any logging to files stderr is fine.

```
/usr/libexec/csi/csiceph -endpoint unix:///tmp/csiceph.sock -nodeid $HOSTNAME -type rbd -drivername ceph-csi-vcanary-rbd  -log_dir '/tmp/' -log_file '/tmp/blabla.log' -logtostderr false

/usr/libexec/csi/csiceph -endpoint unix:///tmp/csiceph.sock -nodeid $HOSTNAME -type rbd -drivername ceph-csi-vcanary-rbd  -log_file '/tmp/blabla.log'

 /usr/libexec/csi/csiceph -endpoint unix:///tmp/csiceph.sock -nodeid $HOSTNAME -type rbd -drivername ceph-csi-vcanary-rbd  -log_dir '/tmp/' -log_file '/tmp/blabla.log'
```

I am testing with something that generates an error from the plugin like:

```
[@ tmp]# csc -e unix:///tmp/csiceph.sock controller create-volume --cap SINGLE_NODE_WRITER,mount,xfs --lim-bytes 100000000 --req-bytes 100000000 --params '' 'not-used?'
missing or empty cluster ID to provision volume from
```

Is there maybe an OS dependency for logging?

**Comment by Madhu-1** [comment]
```bash
$_output/cephcsi --log_file=./log.txt -logtostderr=false -drivername=test --type=rbd
$cat cat log.txt 
Log file created at: 2020/12/18 17:43:24
Running on machine: localhost
Binary: Built with gc go1.13.10 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F1218 17:43:24.432273   22966 driver.go:102] failed to write ceph configuration file (open /etc/ceph/ceph.conf: permission denied)
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc0004b9801, 0xc0000f00e0, 0x83, 0xd5)
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:996 +0xb8
k8s.io/klog/v2.(*loggingT).output(0x29327a0, 0xc000000003, 0x0, 0x0, 0xc0002422a0, 0x267c976, 0x9, 0x66, 0x411f00)
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:945 +0x19d
k8s.io/klog/v2.(*loggingT).printDepth(0x29327a0, 0x3, 0x0, 0x0, 0x1, 0xc00011bc08, 0x1, 0x1)
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:718 +0x15e
k8s.io/klog/v2.FatalDepth(...)
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1449
github.com/ceph/ceph-csi/internal/util.FatalLogMsg(0x18c3736, 0x2c, 0xc00011bcf0, 0x1, 0x1)
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/internal/util/log.go:58 +0xe5
github.com/ceph/ceph-csi/internal/rbd.(*Driver).Run(0xc00011be80, 0x29328a0)
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/internal/rbd/driver.go:102 +0x9b
main.main()
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/cmd/cephcsi.go:183 +0x3b5

goroutine 34 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x29326c0)
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/klog.go:411 +0xd6

goroutine 35 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x29327a0)
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
	/home/mrajanna/workspace/src/github.com/ceph/ceph-csi/vendor/k8s.io/klog/v2/klog.go:416 +0xd6

goroutine 60 [syscall]:
os/signal.signal_recv(0x463e26)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
```
cephcsi is built for the Linux platform it should work on Linux without any issue. I have tested this on the fedora system

**Comment by f1-outsourcing** [comment]
Pffff you are right, indeed if I use '=' with `-log_file=./log.txt -logtostderr=false`, weird that the other arguments allow to be submitted with space.

**Comment by Madhu-1** [comment]
closing this one as not an issue
