### ISSUE TITLE
cephfs create pvc always pending

### ISSUE THREAD

**Issue by yyt6200** [ceph/ceph-csi#1857]
Using rbd can create PVC, but cephfs can't. After testing in toolbox, we get the following error, hoping to get some advice

```
sh-4.4# ceph fs subvolume create myfs stone-test-1 1073741824 csi
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 165, in get_fs_handle
    conn.connect()
  File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 88, in connect
    self.fs.mount(filesystem_name=self.fs_name.encode('utf-8'))
  File "cephfs.pyx", line 739, in cephfs.LibCephFS.mount
cephfs.Error: error calling ceph_mount: Connection timed out [Errno 110]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1177, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/usr/share/ceph/mgr/volumes/module.py", line 426, in handle_command
    return handler(inbuf, cmd)
  File "/usr/share/ceph/mgr/volumes/module.py", line 34, in wrap
    return f(self, inbuf, cmd)
  File "/usr/share/ceph/mgr/volumes/module.py", line 480, in _cmd_fs_subvolume_create
    namespace_isolated=cmd.get('namespace_isolated', False))
  File "/usr/share/ceph/mgr/volumes/fs/volume.py", line 157, in create_subvolume
    with open_volume(self, volname) as fs_handle:
  File "/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 316, in open_volume
    fs_handle = vc.connection_pool.get_fs_handle(volname)
  File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 171, in get_fs_handle
    raise VolumeException(-e.args[0], e.args[1])
TypeError: bad operand type for unary -: 'str'
```

**Comment by Madhu-1** [comment]
>  File "cephfs.pyx", line 739, in cephfs.LibCephFS.mount
cephfs.Error: error calling ceph_mount: Connection timed out [Errno 110]

The above is a connection issue, some kubernetes network plugin might work with RBD but not with CephFS.

**Comment by yyt6200** [comment]
@Madhu-1 
Thank you very much for your reply. My k8s cluster uses the flannel plugin. Does this plugin support cephfs?

**Comment by Madhu-1** [comment]
https://github.com/rook/rook/issues/4006 might help, as you are using Rook to deploy the ceph cluster. I would suggest opening the issue in Rook as cephcsi is not involved in the above issue. Closing for the same reason

**Comment by yyt6200** [comment]
OK,Thank you very much
