### ISSUE TITLE
panic occurred: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by joedborg** [ceph/ceph-csi#1925]
# Describe the bug #

CSI container:
```
goroutine 280 [running]:
runtime/debug.Stack(0x92, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x25
github.com/ceph/ceph-csi/internal/csi-common.panicHandler.func1(0xc0000f3908)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:147 +0xd1
panic(0x1696680, 0x25f0d70)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/ceph/ceph-csi/internal/cephfs.(*ControllerServer).ControllerGetCapabilities(0x0, 0x1a7f4c0, 0xc0006d4570, 0xc00000f5c0, 0x0, 0x4f4497, 0xc0006135f0)
	<autogenerated>:1 +0x5
github.com/container-storage-interface/spec/lib/go/csi._Controller_ControllerGetCapabilities_Handler.func1(0x1a7f4c0, 0xc0006d4570, 0x1777a20, 0xc00000f5c0, 0x0, 0x17, 0xc0006135f0, 0x0)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5633 +0x89
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1a7f4c0, 0xc0006d4570, 0x1777a20, 0xc00000f5c0, 0x85, 0x413600, 0x85, 0x8)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x114
github.com/ceph/ceph-csi/internal/csi-common.panicHandler(0x1a7f4c0, 0xc0006d4570, 0x1777a20, 0xc00000f5c0, 0xc00000f5e0, 0xc0004af9a0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:151 +0x96
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1a7f4c0, 0xc0006d4570, 0x1777a20, 0xc00000f5c0, 0xc0002969a8, 0x1, 0x1, 0x30)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9c
github.com/ceph/ceph-csi/internal/csi-common.logGRPC(0x1a7f4c0, 0xc0006d4570, 0x1777a20, 0xc00000f5c0, 0xc00000f5e0, 0xc0004af9a0, 0x512726, 0x177c1e0, 0xc0006d4570, 0x161fce0)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:134 +0x1ac
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x1a7f4c0, 0xc0006d4570, 0x1777a20, 0xc00000f5c0, 0x1624fa0, 0x2636bf8, 0x1a7f4c0, 0xc0006d4570)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9c
github.com/ceph/ceph-csi/internal/csi-common.contextIDInjector(0x1a7f4c0, 0xc0006d4570, 0x1777a20, 0xc00000f5c0, 0xc00000f5e0, 0xc0004af9a0, 0xc000217200, 0x0, 0xc000296b08, 0x416598)
	/go/src/github.com/ceph/ceph-csi/internal/csi-common/utils.go:128 +0x122
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1a7f4c0, 0xc0006d4540, 0x1777a20, 0xc00000f5c0, 0xc00000f5e0, 0xc00000f600, 0xc000296b78, 0x512726, 0x177c1e0, 0xc0006d4540)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39 +0x15b
github.com/container-storage-interface/spec/lib/go/csi._Controller_ControllerGetCapabilities_Handler(0x17fbd80, 0x0, 0x1a7f4c0, 0xc0006d4540, 0xc000617c20, 0xc0002180c0, 0x1a7f4c0, 0xc0006d4540, 0x0, 0x0)
	/go/src/github.com/ceph/ceph-csi/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5635 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000502300, 0x1a929e0, 0xc0005d4480, 0xc000217200, 0xc000218360, 0x25fe128, 0x0, 0x0, 0x0)
	/go/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000502300, 0x1a929e0, 0xc0005d4480, 0xc000217200, 0x0)
	/go/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:1313 +0xd34
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000047130, 0xc000502300, 0x1a929e0, 0xc0005d4480, 0xc000217200)
	/go/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:722 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/ceph/ceph-csi/vendor/google.golang.org/grpc/server.go:720 +0xa5
E0318 19:42:45.233433       1 utils.go:136] ID: 87 GRPC error: rpc error: code = Internal desc = panic runtime error: invalid memory address or nil pointer dereference
I0318 19:42:45.471413       1 utils.go:132] ID: 88 GRPC call: /csi.v1.Identity/Probe
I0318 19:42:45.471525       1 utils.go:133] ID: 88 GRPC request: {}
I0318 19:42:45.471568       1 utils.go:138] ID: 88 GRPC response: {}
I0318 19:42:45.473190       1 utils.go:132] ID: 89 GRPC call: /csi.v1.Identity/GetPluginInfo
I0318 19:42:45.473277       1 utils.go:133] ID: 89 GRPC request: {}
I0318 19:42:45.473295       1 identityserver-default.go:36] ID: 89 Using default GetPluginInfo
I0318 19:42:45.473362       1 utils.go:138] ID: 89 GRPC response: {"name":"cephfs.csi.ceph.com","vendor_version":"v3.2.1"}
I0318 19:42:45.474162       1 utils.go:132] ID: 90 GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0318 19:42:45.474235       1 utils.go:133] ID: 90 GRPC request: {}
I0318 19:42:45.474352       1 utils.go:138] ID: 90 GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}},{"Type":{"VolumeExpansion":{"type":1}}},{"Type":{"Service":{"type":2}}}]}
I0318 19:42:45.475463       1 utils.go:132] ID: 91 GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0318 19:42:45.475535       1 utils.go:133] ID: 91 GRPC request: {}
E0318 19:42:45.475583       1 utils.go:146] panic occurred: runtime error: invalid memory address or nil pointer dereference
```
CSI Provisioner:
```
I0318 19:58:07.674062       1 csi-provisioner.go:121] Version: v2.0.4
I0318 19:58:07.674197       1 csi-provisioner.go:135] Building kube configs for running in cluster...
I0318 19:58:07.694515       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0318 19:58:07.695721       1 common.go:111] Probing CSI driver for readiness
I0318 19:58:07.695767       1 connection.go:182] GRPC call: /csi.v1.Identity/Probe
I0318 19:58:07.695779       1 connection.go:183] GRPC request: {}
I0318 19:58:07.704987       1 connection.go:185] GRPC response: {}
I0318 19:58:07.705122       1 connection.go:186] GRPC error: <nil>
I0318 19:58:07.705147       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0318 19:58:07.705156       1 connection.go:183] GRPC request: {}
I0318 19:58:07.706031       1 connection.go:185] GRPC response: {"name":"cephfs.csi.ceph.com","vendor_version":"v3.2.1"}
I0318 19:58:07.706144       1 connection.go:186] GRPC error: <nil>
I0318 19:58:07.706169       1 csi-provisioner.go:182] Detected CSI driver cephfs.csi.ceph.com
W0318 19:58:07.706180       1 metrics.go:333] metrics endpoint will not be started because `metrics-address` was not specified.
I0318 19:58:07.706195       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0318 19:58:07.706204       1 connection.go:183] GRPC request: {}
I0318 19:58:07.707358       1 connection.go:185] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}},{"Type":{"VolumeExpansion":{"type":1}}},{"Type":{"Service":{"type":2}}}]}
I0318 19:58:07.707690       1 connection.go:186] GRPC error: <nil>
I0318 19:58:07.707710       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0318 19:58:07.707719       1 connection.go:183] GRPC request: {}
I0318 19:58:07.708804       1 connection.go:185] GRPC response: {}
I0318 19:58:07.708937       1 connection.go:186] GRPC error: rpc error: code = Internal desc = panic runtime error: invalid memory address or nil pointer dereference
F0318 19:58:07.709018       1 csi-provisioner.go:188] Error getting CSI driver capabilities: rpc error: code = Internal desc = panic runtime error: invalid memory address or nil pointer dereference
```

# Environment details #

- Image/version of Ceph CSI driver : quay.io/cephcsi/cephcsi:3.2.1
- Kernel version : 5.4.0-54
- Kubernetes cluster version : 1.20

# Steps to reproduce #

I've tried to manually deploy ceph and the provisioner. Can confirm the volume mounts are correct, with the csi-provisioner.sock socket created. 

# Actual results #

See above.

# Expected behavior #

No crash.

# Logs #

See above.

**Comment by Madhu-1** [comment]
@joedborg can you please provide the provisioner deployment output?

**Comment by joedborg** [comment]
Hi @Madhu-1 Do you mean output from the pod the deployment creates?  It's already above, if that is the case.

**Comment by joedborg** [comment]
https://pastebin.ubuntu.com/p/3bpY5X6WbC/ Here is the output from all of the provisioner components.

**Comment by Rakshith-R** [comment]
Hey @joedborg , can u please share ceph csi deployment yaml you've used to deploy the provisioner. Did u change the args supplied to the csi-cephfsplugin?

**Comment by Rakshith-R** [comment]
Hey @joedborg , can you please share the deployment yaml file you've used to deploy the provisioner?

**Comment by Rakshith-R** [comment]
https://github.com/ceph/ceph-csi/blob/62ae17e2634430c0c392c881bbe372d0a46a8ccd/deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml#L108-L122
@joedborg  Make sure args for provisioner deployment is the same as above. 
You will need to deploy [cephfs nodeplugin](https://github.com/ceph/ceph-csi/blob/devel/deploy/cephfs/kubernetes/csi-cephfsplugin.yaml) as well.

**Comment by Rakshith-R** [comment]
### Steps to reproduce
Change `- "--controllerserver=true" `  to `- "--nodeserver=true"` in cephfs provisioner deployment args to reproduce the issue
https://github.com/ceph/ceph-csi/blob/62ae17e2634430c0c392c881bbe372d0a46a8ccd/deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml#L108-L122

---
### Source of issue 
https://github.com/ceph/ceph-csi/blob/62ae17e2634430c0c392c881bbe372d0a46a8ccd/internal/csi-common/controllerserver-default.go#L59-L67

cs.Driver is `nil` in case only `- "--nodeserver=true"` is set in provisioner deployment(which is the incorrect way to deploy it). 

Fixes: 
- Add a check `cs.Driver!=nil` in [controllerserver-default](https://github.com/ceph/ceph-csi/blob/62ae17e2634430c0c392c881bbe372d0a46a8ccd/internal/csi-common/controllerserver-default.go)
- Or move `ControllerGetCapabilities` to [cephfs controller server](https://github.com/ceph/ceph-csi/blob/devel/internal/cephfs/controllerserver.go) and [rbd controller server](https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/controllerserver.go)

hey @Madhu-1 , PTAL and let me know which fix is better in this case.

**Comment by Madhu-1** [comment]
Nodeserver should not be set on the deployment because it has to set/start the controllerserver. you can add the Driver!=nil check and return proper errro message.

**Comment by joedborg** [comment]
Thank you @Rakshith-R, that's exactly what the issue was.  I had nodeserver set for both the nodeplugin and the provisioner instances of ceph-csi containers.  Have fixed it in the provisioner instance and it works fine.
