### ISSUE TITLE
cephcsi:v3.4.0-amd64 - failed to write ceph configuration file 

### ISSUE THREAD

**Issue by jeremiepradet** [ceph/ceph-csi#2614]
# Describe the bug #

I'm trying to use cephcsi:v3.4.0-amd64 to have Persistent Volumes but I can't creat PVC.
When I try with canary version, I can create PVC and write data in PVC.

Why v3.4.0-amd64 I find error bellow:
```bash
kubectl logs csi-rbdplugin-7x727 -c driver-registrar -c csi-rbdplugin
I1103 08:54:04.541361   24542 cephcsi.go:167] Driver version: v3.4.0 and Git version: 94ef181bc866c8ccaf507de66f213b26608309ff
I1103 08:54:04.541993   24542 cephcsi.go:212] Starting driver type: rbd with name: rbd.csi.ceph.com
F1103 08:54:04.542097   24542 driver.go:110] failed to write ceph configuration file (open /etc/ceph/ceph.conf: read-only file system)
goroutine 1 [running]:
```

# Environment details #

- Image/version of Ceph CSI driver :  v3.4.0-amd64
- Kubernetes cluster version : v1.20.5
- Ceph cluster version : 15.2.14

# Steps to reproduce #

1. I follow the Ceph documentation [https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/](https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/)
2. Modify csi-rbdplugin.yaml and csi-rbdplugin-provisioner.yaml files to change canary by v3.4.0-amd64 or v3.4.0
file: csi-rbdplugin-provisioner.yaml
```diff
-           image: quay.io/cephcsi/cephcsi:canary
+          image: quay.io/cephcsi/cephcsi:v3.4.0-amd64
...
-          image: quay.io/cephcsi/cephcsi:canary
+         image: quay.io/cephcsi/cephcsi:v3.4.0-amd64
...
-         image: quay.io/cephcsi/cephcsi:canary
+        image: quay.io/cephcsi/cephcsi:v3.4.0-amd64
```
3. Create PVC type fileSystem
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ceph-fs1
  namespace: mynamesapce
  labels:
    driver: ceph
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: sc-ceph
```

# Actual results #

Status PVC:
```bash
kubectl get pvc
NAME           STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-ceph-fs1   Pending                                      sc-ceph        30m
```
Details
```bash

kubectl describe pvc pvc-ceph-fs1 
Name:          pvc-ceph-fs1
Namespace:     mynamesapce
StorageClass:  sc-ceph
Status:        Pending
Volume:        
Labels:        driver=ceph
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       webapp1-6d7cfcd77f-kn9cc
Events:
  Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  ExternalProvisioning  25m (x26 over 31m)    persistentvolume-controller  waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator
  Normal  ExternalProvisioning  16m (x26 over 22m)    persistentvolume-controller  waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator
  Normal  ExternalProvisioning  3m55s (x41 over 13m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator
```
Status POD:
```bash
k get pods
NAME                                        READY   STATUS             RESTARTS   AGE
csi-rbdplugin-7x727                         2/3     CrashLoopBackOff   11         36m
csi-rbdplugin-8zfrk                         2/3     CrashLoopBackOff   11         36m
csi-rbdplugin-mspsq                         2/3     CrashLoopBackOff   11         36m
csi-rbdplugin-p46r7                         2/3     Error              16         36m
csi-rbdplugin-provisioner-54bcb4bc9-bd9w4   6/7     CrashLoopBackOff   12         36m
csi-rbdplugin-provisioner-54bcb4bc9-dnhn6   6/7     CrashLoopBackOff   12         36m
csi-rbdplugin-provisioner-54bcb4bc9-vs4bw   6/7     CrashLoopBackOff   12         36m
webapp1-6d7cfcd77f-kn9cc                    0/1     Pending            0          36m
```
Log Pod  csi-rbdplugin
```bash
kubectl logs csi-rbdplugin-7x727 -c driver-registrar -c csi-rbdplugin
I1103 08:54:04.541361   24542 cephcsi.go:167] Driver version: v3.4.0 and Git version: 94ef181bc866c8ccaf507de66f213b26608309ff
I1103 08:54:04.541993   24542 cephcsi.go:212] Starting driver type: rbd with name: rbd.csi.ceph.com
F1103 08:54:04.542097   24542 driver.go:110] failed to write ceph configuration file (open /etc/ceph/ceph.conf: read-only file system)
goroutine 1 [running]:
```

Shoud I change any config files ?

**Comment by nixpanic** [comment]
Please verify that you use the `.yaml` deployment files that match the version of the image. There have been changes to allow a ConfigMap to be specified as source for the `/etc/ceph/ceph.conf` file, which are not part of the 3.4 release.

See #2476 for details.

**Comment by jeremiepradet** [comment]
Thank for your reply.
I'm looking your solution.

**Comment by jeremiepradet** [comment]
The driver works better why good files version
So I used files in https://github.com/ceph/ceph-csi/tree/v3.4.0/deploy/rbd/kubernetes

Thank for your quick answer.
