### ISSUE TITLE
ci: Jenkins Jobs Builder seems incompatible with latest urllib3

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#3946]
# Describe the bug #

The [jjb-deply CI job](https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/job/jjb-deploy/) fails deploying updated Jenkins Jobs:
```
make: Entering directory '/opt/build/deploy'
cd /opt/build/deploy/../ && jenkins-jobs update --delete-old jobs
INFO:jenkins_jobs.cli.subcommand.base:Updating jobs in [PosixPath('jobs')] ([])
INFO:root:Caching type properties of properties = jenkins_jobs.modules.properties:Properties
INFO:root:Caching type triggers of triggers = jenkins_jobs.modules.triggers:Triggers
INFO:root:Caching type scm of scm = jenkins_jobs.modules.scm:SCM
INFO:root:Caching type parameters of parameters = jenkins_jobs.modules.parameters:Parameters
INFO:jenkins_jobs.builder:Number of jobs generated:  17
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 822, in get_info
    return json.loads(self.jenkins_open(
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 560, in jenkins_open
    return self.jenkins_request(req, add_crumb, resolve_auth).text
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 576, in jenkins_request
    self.maybe_add_crumb(req)
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 373, in maybe_add_crumb
    response = self.jenkins_open(requests.Request(
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 560, in jenkins_open
    return self.jenkins_request(req, add_crumb, resolve_auth).text
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 579, in jenkins_request
    self._request(req))
  File "/usr/local/lib/python3.9/site-packages/jenkins/__init__.py", line 553, in _request
    return self._session.send(r, **_settings)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 483, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 119, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7fe6ec472de0>, but it must be an int, float or None.
```

[StackOverflow has a report](https://stackoverflow.com/questions/76180798/jenkins-job-failing-for-urllib3-valueerror-timeout-value-connect-was-object-o) with a solution that addresses the issue. Once a Jenkins Jobs Builder is compatible with the latest urllib3 package, the workaround can be removed.

**Comment by nixpanic** [comment]
The [upstream reported issue](https://storyboard.openstack.org/#!/story/2010752) suggests adding a `timeout` value in the Jenkins Jobs Builder configuration. This looks like a nicer workaround than downgrading urllib3.
