### ISSUE TITLE
cephfs-csi not able to handle massive PVC create requests

### ISSUE THREAD

**Issue by ekuric** [ceph/ceph-csi#516]
# Describe the bug #

cephfs-csi not able to handle massive PVC create requests 

In this test we created 
-> one project 
-> inside project 900 pods with 1 GB PVC from csi-cephfs.

Pods fails to mount PVC

# Environment details #
OCP 4.1 
```
 oc get clusterversion 
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.1.0-0.nightly-2019-07-31-005945   True        False         15h     Cluster version is 4.1.0-0.nightly-2019-07-31-005945
``` 
- Image/version of Ceph CSI driver
```
# grep image operator-openshift-with-csi.yaml 
        image: rook/ceph:master
root@ip-172-31-81-56: ~/rook-v4.2-aws-test/cluster/examples/kubernetes/ceph # grep image cluster.yaml 
    # The container image used to launch the Ceph daemon pods (mon, mgr, osd, mds, rgw).
    image: ceph/ceph:v14.2.2-20190722
root@ip-172-31-81-56: ~/rook-v4.2-aws-test/cluster/examples/kubernetes/ceph # git describe 
v1.0.0-312-ge5779f7
root@ip-172-31-81-56: ~/rook-v4.2-aws-test/cluster/examples/kubernetes/ceph # git branch 
* master
root@ip-172-31-81-56: ~/rook-v4.2-aws-test/cluster/examples/kubernetes/ceph # git log --pretty=oneline | head -5
e5779f79d59b4ce58d1879b100859a2e073ea736 Merge pull request #3533 from ethan-daocloud/patch-1
0acdf9a4f1d8d6cc1834a58a246b16a7d22b2028 Merge pull request #3532 from zgfh/patch-1
aeb47eaf521d7d2fcb47b71777a6b829c42883a4 fix misspelling in bug_report.md
d50c9ef3bf0114f6eabdce1ac1d2c104722a6bf5 Merge pull request #3530 from renekalff/fix-k8s-ownerreferences
25780878ebee5b1326c550b15fe06390c2e7f181 Make the ownerreference name match the cluster name referenced
``` 
- Kubernetes cluster version
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+dafd0c6", GitCommit:"dafd0c6", GitTreeState:"clean", BuildDate:"2019-04-10T03:10:23Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+572d00b", GitCommit:"572d00b", GitTreeState:"clean", BuildDate:"2019-07-28T14:53:54Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
``` 
- Logs
All pods which fail to mount PVC have below error message 

```
# cat pod_pvc-pod-xlh85.txt
Name:               pvc-pod-xlh85
Namespace:          pvcscale0
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-0-163-194.us-west-2.compute.internal/10.0.163.194
Start Time:         Thu, 01 Aug 2019 08:46:54 +0000
Labels:             name=pvc-pod-877
Annotations:        openshift.io/scc: node-exporter
Status:             Pending
IP:                 
Containers:
  fio-pod:
    Container ID:   
    Image:          quay.io/openshift-scale/scale-ci-workload
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/pvcmount from persistentvolume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2nxm5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  persistentvolume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pvck22t37po41
    ReadOnly:   false
  default-token-2nxm5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2nxm5
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                                                 Message
  ----     ------                  ----                  ----                                                 -------
  Warning  FailedScheduling        9m17s (x21 over 13m)  default-scheduler                                    pod has unbound immediate PersistentVolumeClaims (repeated 6 times)
  Normal   Scheduled               9m11s                 default-scheduler                                    Successfully assigned pvcscale0/pvc-pod-xlh85 to ip-10-0-163-194.us-west-2.compute.internal
  Normal   SuccessfulAttachVolume  9m10s                 attachdetach-controller                              AttachVolume.Attach succeeded for volume "pvc-34ca4cbc-b438-11e9-90f8-02c74cbd389e"
  Warning  FailedMount             7m8s                  kubelet, ip-10-0-163-194.us-west-2.compute.internal  Unable to mount volumes for pod "pvc-pod-xlh85_pvcscale0(34cb8f04-b438-11e9-90f8-02c74cbd389e)": timeout expired waiting for volumes to attach or mount for pod "pvcscale0"/"pvc-pod-xlh85". list of unmounted volumes=[persistentvolume default-token-2nxm5]. list of unattached volumes=[persistentvolume default-token-2nxm5]
  Warning  FailedMount             4m51s                 kubelet, ip-10-0-163-194.us-west-2.compute.internal  MountVolume.MountDevice failed for volume "pvc-34ca4cbc-b438-11e9-90f8-02c74cbd389e" : rpc error: code = Internal desc = cannot get process pid while running ceph [-m 172.30.58.149:6789,172.30.182.233:6789,172.30.187.168:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json]: fork/exec /usr/bin/ceph: resource temporarily unavailable:
  Warning  FailedMount             4m45s                 kubelet, ip-10-0-163-194.us-west-2.compute.internal  MountVolume.MountDevice failed for volume "pvc-34ca4cbc-b438-11e9-90f8-02c74cbd389e" : rpc error: code = Internal desc = an error occurred while running (10115) ceph [-m 172.30.58.149:6789,172.30.182.233:6789,172.30.187.168:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json]: exit status 1: Traceback (most recent call last):
  File "/usr/bin/ceph", line 1263, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1179, in main
    prefix='get_command_descriptions')
  File "/usr/lib/python2.7/site-packages/ceph_argparse.py", line 1463, in json_command
    raise RuntimeError('"{0}": exception {1}'.format(argdict, e))
RuntimeError: "None": exception "['{"prefix": "get_command_descriptions"}']": exception can't start new thread
  Warning  FailedMount  4m37s  kubelet, ip-10-0-163-194.us-west-2.compute.internal  MountVolume.MountDevice failed for volume "pvc-34ca4cbc-b438-11e9-90f8-02c74cbd389e" : rpc error: code = Internal desc = an error occurred while running (10401) ceph [-m 172.30.58.149:6789,172.30.182.233:6789,172.30.187.168:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json]: exit status 1: Traceback (most recent call last):
  File "/usr/bin/ceph", line 1263, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1179, in main
    prefix='get_command_descriptions')
  File "/usr/lib/python2.7/site-packages/ceph_argparse.py", line 1463, in json_command
    raise RuntimeError('"{0}": exception {1}'.format(argdict, e))
RuntimeError: "None": exception "['{"prefix": "get_command_descriptions"}']": exception can't start new thread
  Warning  FailedMount  4m30s  kubelet, ip-10-0-163-194.us-west-2.compute.internal  MountVolume.MountDevice failed for volume "pvc-34ca4cbc-b438-11e9-90f8-02c74cbd389e" : rpc error: code = Internal desc = an error occurred while running (10532) ceph [-m 172.30.58.149:6789,172.30.182.233:6789,172.30.187.168:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json]: signal: aborted (core dumped): Thread::try_create(): pthread_create failed with error 11/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.2/rpm/el7/BUILD/ceph-14.2.2/src/common/Thread.cc: In function 'void Thread::create(const char*, size_t)' thread 7fb5adeda700 time 2019-08-01 08:51:34.317831
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.2/rpm/el7/BUILD/ceph-14.2.2/src/common/Thread.cc: 157: FAILED ceph_assert(ret == 0)
 ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x14a) [0x7fb5b5ab8046]
 2: (ceph::__ceph_assertf_fail(char const*, char const*, int, char const*, char const*, ...)+0) [0x7fb5b5ab8214]
 3: (()+0x2d39d2) [0x7fb5b5b3c9d2]
 4: (SafeTimer::init()+0x65) [0x7fb5b5b43835]
 5: (()+0x95753) [0x7fb5be6ae753]
 6: (rados_connect()+0x1e) [0x7fb5be64946e]
 7: (()+0x306d6) [0x7fb5be9856d6]
 8: (PyEval_EvalFrameEx()+0x730a) [0x7fb5c13ac20a]
 9: (PyEval_EvalCodeEx()+0x7ed) [0x7fb5c13ae03d]
 10: (PyEval_EvalFrameEx()+0x663c) [0x7fb5c13ab53c]
 11: (PyEval_EvalFrameEx()+0x67bd) [0x7fb5c13ab6bd]
 12: (PyEval_EvalCodeEx()+0x7ed) [0x7fb5c13ae03d]
 13: (()+0x70978) [0x7fb5c1337978]
 14: (PyObject_Call()+0x43) [0x7fb5c1312a63]
 15: (()+0x5aa55) [0x7fb5c1321a55]
 16: (PyObject_Call()+0x43) [0x7fb5c1312a63]
 17: (PyEval_CallObjectWithKeywords()+0x47) [0x7fb5c13a48f7]
 18: (()+0x115822) [0x7fb5c13dc822]
 19: (()+0x7dd5) [0x7fb5c10b2dd5]
 20: (clone()+0x6d) [0x7fb5c06d302d]
  Warning  FailedMount  4m21s  kubelet, ip-10-0-163-194.us-west-2.compute.internal  MountVolume.MountDevice failed for volume "pvc-34ca4cbc-b438-11e9-90f8-02c74cbd389e" : rpc error: code = Internal desc = an error occurred while running (10854) ceph [-m 172.30.58.149:6789,172.30.182.233:6789,172.30.187.168:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json]: exit status 1: Traceback (most recent call last):
  File "/usr/bin/ceph", line 1263, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1179, in main
    prefix='get_command_descriptions')
  File "/usr/lib/python2.7/site-packages/ceph_argparse.py", line 1463, in json_command
    raise RuntimeError('"{0}": exception {1}'.format(argdict, e))
RuntimeError: "None": exception "['{"prefix": "get_command_descriptions"}']": exception can't start new thread
  Warning  FailedMount  4m8s  kubelet, ip-10-0-163-194.us-west-2.compute.internal  MountVolume.MountDevice failed for volume "pvc-34ca4cbc-b438-11e9-90f8-02c74cbd389e" : rpc error: code = Internal desc = an error occurred while running (11247) ceph [-m 172.30.58.149:6789,172.30.182.233:6789,172.30.187.168:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json]: exit status 1: Traceback (most recent call last):
  File "/usr/bin/ceph", line 1263, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1179, in main
    prefix='get_command_descriptions')
  File "/usr/lib/python2.7/site-packages/ceph_argparse.py", line 1463, in json_command
    raise RuntimeError('"{0}": exception {1}'.format(argdict, e))
RuntimeError: "None": exception "['{"prefix": "get_command_descriptions"}']": exception can't start new thread
  Warning  FailedMount  3m43s  kubelet, ip-10-0-163-194.us-west-2.compute.internal  MountVolume.MountDevice failed for volume "pvc-34ca4cbc-b438-11e9-90f8-02c74cbd389e" : rpc error: code = Internal desc = an error occurred while running (12031) ceph [-m 172.30.58.149:6789,172.30.182.233:6789,172.30.187.168:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json]: exit status 1: Traceback (most recent call last):
  File "/usr/bin/ceph", line 1263, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1179, in main
    prefix='get_command_descriptions')
  File "/usr/lib/python2.7/site-packages/ceph_argparse.py", line 1463, in json_command
    raise RuntimeError('"{0}": exception {1}'.format(argdict, e))
RuntimeError: "None": exception "['{"prefix": "get_command_descriptions"}']": exception can't start new thread
  Warning  FailedMount  2m35s (x2 over 4m51s)  kubelet, ip-10-0-163-194.us-west-2.compute.internal  Unable to mount volumes for pod "pvc-pod-xlh85_pvcscale0(34cb8f04-b438-11e9-90f8-02c74cbd389e)": timeout expired waiting for volumes to attach or mount for pod "pvcscale0"/"pvc-pod-xlh85". list of unmounted volumes=[persistentvolume]. list of unattached volumes=[persistentvolume default-token-2nxm5]
  Warning  FailedMount  18s (x3 over 3m7s)     kubelet, ip-10-0-163-194.us-west-2.compute.internal  (combined from similar events): Unable to mount volumes for pod "pvc-pod-xlh85_pvcscale0(34cb8f04-b438-11e9-90f8-02c74cbd389e)": timeout expired waiting for volumes to attach or mount for pod "pvcscale0"/"pvc-pod-xlh85". list of unmounted volumes=[persistentvolume]. list of unattached volumes=[persistentvolume default-token-2nxm5]
root@ip-172-31-81-56: ~/ocp-automation/1 # 
```

**Comment by humblec** [comment]
@ekuric are you able to create a single PVC of CephFS CSI in this setup ?

**Comment by humblec** [comment]
@poornimag

**Comment by ekuric** [comment]
images 
``` 
# oc describe pod |grep Image:
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-attacher:v1.1.1
    Image:         quay.io/k8scsi/csi-provisioner:v1.2.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-provisioner:v1.2.0
    Image:         quay.io/k8scsi/csi-attacher:v1.1.1
    Image:         quay.io/k8scsi/csi-snapshotter:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/cephcsi/cephcsi:canary
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         rook/ceph:master
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         rook/ceph:master
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         rook/ceph:master
    Image:         ceph/ceph:v14.2.2-20190722
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
    Image:         rook/ceph:master
```

**Comment by ekuric** [comment]
@humblec 
yes, 
```
oc get pvc |grep Bound |wc -l
900
root@ip-172-31-81-56: ~/ocp-automation # 
```
pods are not starting - error message see above 

```
# oc get pods |grep -v Run |wc -l
478
root@ip-172-31-81-56: ~/ocp-automation # oc get pods |grep -v Run |head -10 
NAME            READY   STATUS              RESTARTS   AGE
pvc-pod-2774c   0/1     ContainerCreating   0          37m
pvc-pod-27fm7   0/1     ContainerCreating   0          36m
pvc-pod-28cd4   0/1     ContainerCreating   0          36m
pvc-pod-2b97s   0/1     ContainerCreating   0          37m
pvc-pod-2chm2   0/1     ContainerCreating   0          36m
pvc-pod-2f9jh   0/1     ContainerCreating   0          36m
pvc-pod-2fcm7   0/1     ContainerCreating   0          36m
pvc-pod-2fwx2   0/1     ContainerCreating   0          38m
pvc-pod-2gd8x   0/1     ContainerCreating   0          39m
```
424 pods started fine 

``` 
# oc get pods |grep Run |wc -l
424
``` 
with rbd-csi started all 900 without issue.

**Comment by humblec** [comment]
Thanks for the additional info. Lets take a look at this.

**Comment by humblec** [comment]
Warning  FailedMount             4m51s                 kubelet, ip-10-0-163-194.us-west-2.compute.internal  MountVolume.MountDevice failed for volume "pvc-34ca4cbc-b438-11e9-90f8-02c74cbd389e" : rpc error: code = Internal desc = cannot get process >

pid while running ceph [-m 172.30.58.149:6789,172.30.182.233:6789,172.30.187.168:6789 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json]: fork/exec /usr/bin/ceph: resource temporarily unavailable:

>

This looks to be caused by the PID issue we are aware of . @ndevos can you provide the test image to @ekuric with the PID fix.

**Comment by nixpanic** [comment]
PR #517 is expected to address issues where the PID Limit is reached.

**Comment by ekuric** [comment]
Issue not visible with image that has adapted --pidlimit @nixpanic @humblec @Madhu-1

**Comment by Madhu-1** [comment]
awesome Thanks @ekuric for testing, @humblec can we merge the PR

**Comment by humblec** [comment]
> Issue not visible with image that has adapted --pidlimit @nixpanic @humblec @Madhu-1

Great!! Thanks for the experiment and sharing the result!
